import {Blog} from './blog'
export const Blogs:Blog[]=
[{"id":1,"title":"Sweet November","content":"Corrosion of internal genitourinary organs","like":1,"dislike":1,"dateUpload":"8/5/2021"},
{"id":2,"title":"Polite People (Kurteist fólk)","content":"Newborn health examination","like":2,"dislike":2,"dateUpload":"5/24/2022"},
{"id":3,"title":"Vampire Hunter D: Bloodlust (Banpaia hantâ D)","content":"Toxic effect of ingested mushrooms, assault","like":3,"dislike":3,"dateUpload":"5/12/2022"},
{"id":4,"title":"Remington and the Curse of the Zombadings","content":"Abnormal level of hormones in specimens from respiratory organs and thorax","like":4,"dislike":4,"dateUpload":"9/3/2021"},
{"id":5,"title":"Big Jake","content":"Unspecified fracture of shaft of unspecified femur","like":5,"dislike":5,"dateUpload":"8/8/2021"},
{"id":6,"title":"Life of a King","content":"Laceration of unspecified blood vessel at ankle and foot level, left leg, sequela","like":6,"dislike":6,"dateUpload":"9/28/2021"},
{"id":7,"title":"Boys Don't Cry (Chlopaki nie placza)","content":"Other severe and complicated Plasmodium falciparum malaria","like":7,"dislike":7,"dateUpload":"11/15/2021"},
{"id":8,"title":"Escape (Flukt)","content":"Assault by knife, initial encounter","like":8,"dislike":8,"dateUpload":"8/7/2021"},
{"id":9,"title":"Canterbury Tales, The (I racconti di Canterbury)","content":"Laceration of other specified intrathoracic organs","like":9,"dislike":9,"dateUpload":"3/25/2022"},
{"id":10,"title":"It's a Boy Girl Thing","content":"Nondisplaced fracture of proximal phalanx of left lesser toe(s), subsequent encounter for fracture with routine healing","like":10,"dislike":10,"dateUpload":"6/9/2021"},
{"id":11,"title":"Joke, The (Zert)","content":"Maternal care for Anti-A sensitization, first trimester, fetus 2","like":11,"dislike":11,"dateUpload":"4/16/2022"},
{"id":12,"title":"Poor Little Rich Girl","content":"Toxic effect of nitrogen oxides, accidental (unintentional), sequela","like":12,"dislike":12,"dateUpload":"6/11/2021"},
{"id":13,"title":"Sunnyside","content":"Pedestrian with other conveyance injured in collision with railway train or railway vehicle, unspecified whether traffic or nontraffic accident","like":13,"dislike":13,"dateUpload":"7/29/2021"},
{"id":14,"title":"Bon Voyage","content":"Crushing injury of shoulder and upper arm, unspecified arm, subsequent encounter","like":14,"dislike":14,"dateUpload":"5/9/2022"},
{"id":15,"title":"The Key","content":"Other specified injuries of unspecified wrist, hand and finger(s), sequela","like":15,"dislike":15,"dateUpload":"9/4/2021"},
{"id":16,"title":"Frank","content":"Corrosion of first degree of unspecified multiple fingers (nail), not including thumb, initial encounter","like":16,"dislike":16,"dateUpload":"5/13/2022"},
{"id":17,"title":"How I Killed My Father","content":"Strain of flexor muscle, fascia and tendon of unspecified thumb at forearm level","like":17,"dislike":17,"dateUpload":"7/6/2021"},
{"id":18,"title":"Rope","content":"Displaced fracture of base of fifth metacarpal bone. left hand","like":18,"dislike":18,"dateUpload":"4/2/2022"},
{"id":19,"title":"Death and the Maiden","content":"Other specific arthropathies, not elsewhere classified, unspecified elbow","like":19,"dislike":19,"dateUpload":"1/6/2022"},
{"id":20,"title":"Hamlet","content":"Premenstrual dysphoric disorder","like":20,"dislike":20,"dateUpload":"7/16/2021"}]